apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus # label for the pod being created
    spec:
      containers:
        - name: event-bus
          image: boisoth/event-bus:latest
--- # create another object
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector: # Tell service what pods it will allow access to
    app: event-bus # From deployment template label for pod
  type: ClusterIP
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005