apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  selector:
    app: posts # telling the service to find all pods named app: posts, template label name
  type: NodePort # if you don't specify, it defaults to ClusterIp
  ports:
    - name: posts # array
      protocol: TCP
      port: 4000
      targetPort: 4000